---
title: "Assignment 1"
author: "AJ Zekanoski"
date: "1/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(ggfortify)
library(readxl)
library(gghighlight)
library(lubridate)
library(plotly)
library(patchwork)
library(palmerpenguins)
library(here)
```

#### Read in the Sierra Amphibians xlsx data and wrangle a bit
```{r}
sierra_amphibians <- read_excel(here("data", "sierra_amphibians.xlsx")) %>% 
  filter(amphibian_life_stage %in% c("Tadpole", "Adult", "SubAdult")) %>%
  filter(amphibian_species == "RAMU")
```


#### Wrangle some more w/lubridate to get the year in its own column and then count observations
```{r}
sierra_amphibians_2 <- sierra_amphibians %>% 
  mutate(survey_date = ymd(survey_date)) %>% 
  mutate(year = year(survey_date)) %>% 
  count(year, amphibian_life_stage, wt = amphibian_number) %>% 
  rename(count = n)
```


#### Counts of mountain yellow-legged frog plotted with ggplot
```{r}
ggplot(data = sierra_amphibians_2, aes(x = year, y = count)) +
  facet_wrap(~amphibian_life_stage, scales = "free") +
  geom_col(fill = "yellow") +
  labs(x = "Year", y = "Abundance of Mountain Yellow-Legged Frogs") +
  theme_dark()

```


#### Filter again to only have mountain yellow frogs in the adult and subadult life stages.
```{r}
sierra_amphibians_3 <- sierra_amphibians %>% 
  filter(amphibian_life_stage %in% c("Adult", "SubAdult"))
```

#### Rename the Lake Id column and get counts of frogs in top five lakes. 

