---
title: "Task2"
author: "AJ Zekanoski"
date: "1/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(ggfortify)
library(readxl)
library(gghighlight)
library(lubridate)
library(plotly)
library(patchwork)
library(here)
```


#### Describe the data and the variables I will be exploring.


#### Read in the global climate data and wrangle to set up for principle components analysis. 
```{r}
world_data <- read_csv(here("data", "world_env_vars.csv")) %>% 
  clean_names() %>% 
  select(cropland_cover, tree_canopy_cover, rain_mean_annual, isothermality) %>% 
  rename(Crop.Cover = cropland_cover) %>% 
  rename(Tree.Canopy.Cover = tree_canopy_cover) %>% 
  rename(Mean.Annual.Rainfall = rain_mean_annual) %>% 
  rename(Isothermality = isothermality) %>% 
  drop_na() %>% 
  scale() %>% 
  prcomp

world_complete <- read_csv(here("data", "world_env_vars.csv")) %>% 
  drop_na(cropland_cover, tree_canopy_cover, rain_mean_annual, isothermality) %>% 
  clean_names()

world_pca <- autoplot(world_data,
         data = world_complete,
         colour = "ivory4",
         loadings = TRUE,
         loadings.colour = "green",
         loadings.label = TRUE,
         loadings.label.hjust = 1.1)
  theme_minimal()
  
world_pca
```


#### Give the World PCA plot a nice caption

```{r, fig.cap = "**Figure 1**. Princple components analysis exploring relationships between isothermality, mean annual rainfall, tree canopy cover, and crop cover for 231 countries."}
world_pca
```


